version: 0.1  
log:  
    level: info
    formatter: json
    fields:
        service: registry
        environment: staging
        source: registry
http:  
    addr: :5000
    host: {{domain_name}}
    secret: {{http_secret}}
storage:  
    filesystem:
        rootdirectory: /var/lib/registry