version: '2'

networks:
  default:
    driver: bridge

services:
  proxy:
    image: jwilder/nginx-proxy
    volumes:
      - /opt/docker/registry-nginx-proxy-letsencrypt/volumes/nginx-certs:/etc/nginx/certs:ro
      - /opt/docker/registry-nginx-proxy-letsencrypt/volumes/nginx-vhost.d:/etc/nginx/vhost.d
      - /opt/docker/registry-nginx-proxy-letsencrypt/volumes/htpasswd:/etc/nginx/htpasswd
      - /usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    ports:
      - "80:80"
      - "443:443"
    networks:
      - default
    restart: always

  companion_proxy:
    image: jrcs/letsencrypt-nginx-proxy-companion
    depends_on: 
      - proxy
    volumes_from:
      - proxy
    volumes:
      - /opt/docker/registry-nginx-proxy-letsencrypt/volumes/nginx-certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - default
    restart: always

  registry:
    image: registry:2.2
    depends_on: 
      - proxy
    environment:
      - VIRTUAL_HOST=registry.arthurbarros.com
      - LETSENCRYPT_HOST=registry.arthurbarros.com
      - LETSENCRYPT_EMAIL=arthbarros@gmail.com
    volumes:
      - /opt/docker/registry-nginx-proxy-letsencrypt/volumes/registry/config/config.yml:/etc/docker/registry/config.yml
    networks:
      - default
    restart: always
    